### ISSUE TITLE
Update docs - history-and-changes.html

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/feature-requests#50]
Update https://docs.osmosis.zone/history-and-changes.html with a history of changes from https://github.com/osmosis-labs/osmosis/releases?page=2. 

The markdown can be copied by clicking on the edit button for the history of changes:

![image](https://user-images.githubusercontent.com/13665117/147967335-1249e447-d078-4208-a68d-e0fcd1ee39d3.png)

Ideally we add the following: 
```
## {date} -  {title}
{changes}

```

# Example

## Aug 03, 2021 - v2.0.0 Governance Patch Upgrade

This upgrade is meant as a patch that must be hard forked in, due to a bug in [proposal 16](https://www.mintscan.io/osmosis/proposals/16) breaking on-chain governance of Osmosis. Details of the bug are at the bottom.

UPDATE: The version that will be used on-chain will not be this version, due to a bug in the cosmos-sdk version v0.42.7

This upgrade includes
* Fixing the immediate governance issue, by changing the min_deposit parameter to what was intended
* Fixing the bug in min_commission_rate, that allowed validators to create a validator with a lower rate than the minimum. It also bumps up all validators to the minimum.
* Update to Cosmos-SDK v0.42.7, which fixes state syncing.

## Governance Bug

In proposal 16, the 'min_deposit' value on the proposal was set to 500**osmo** and not the intended 500000000uosmo. On chain, the denomination "osmo" doesn't exist, there is only "uosmo" (Similar to how on Bitcoin there are only sats).

Due to this parameter change, a sufficient governance deposit to enter on-chain voting must be in Osmo, which is a denomination that does not exist on chain. Thus no new governance proposals can enter a voting period and get decided on chain.

**Comment by czarcas7ic** [comment]
@daniel-farina see https://docs.osmosis.zone/history-and-changes.html , should be good to close if you're happy with it!

**Comment by daniel-farina** [comment]
looks amazing!
