### ISSUE TITLE
Add bonded liquidity percentage metric to incentivized pools on the frontend

### ISSUE THREAD

**Issue by AndyRusso** [osmosis-labs/feature-requests#75]
I would like to see the percentage of bonded liquidity from the TVL in incentivized pools.
It would be great if this information was dynamic and located next to the TVL amount in the incentivized pool description.
This would let everyone calculate the proper APR for bonded liquidity, which would allow everyone to make more reasonable decisions for bonding and unbonding liquidity.
This would make the interface more friendly and easier to understand.
![image](https://github.com/osmosis-labs/feature-requests/assets/88431411/03952fc9-9ece-4364-8e26-63c4a3580cbf)

**Comment by jonator** [comment]
Is your wallet connected? If it is, you should see this graphic that uses a single bar to roughly illustrate your distribution:
<img width="1082" alt="Screenshot 2023-07-31 at 7 31 09 AM" src="https://github.com/osmosis-labs/feature-requests/assets/4606373/804bebf2-1464-40cf-a110-05b59e895dcb">

**Comment by jonator** [comment]
Or are you talking about the global bonded %?

**Comment by AndyRusso** [comment]
I need a metric for bonded liquidity percentage for a specific incentivized pool (any pool with incentives).
This metric affects the decision whether or not to bond my liquidity. If the incentivized pool has 100% bonded liquidity, then I can rely on the APR below in the "Bond liquidity" section. If the bonded liquidity in the incentivized pool is less than 100%, for example 50%, then I will receive double the incentives regardless of my share.
This is a very important metric. Currently it's possible to calculate that by analyzing the info.osmosis.zone website, but it is very hard and complicated.

So to answer your question: yes, I need the global bonded liquidity percent for a specific incentivized pool.

**Comment by AndyRusso** [comment]
@jonator hello, is my description informative enough? If required I can gladly answer all your questions.
